### ISSUE TITLE
m_best_lap_time_in_ms erroneous data

### ISSUE THREAD

**Issue by rcastley** [chrishannam/Telemetry-F1-2021#7]
Hi,

Firstly, great Python library, thank you :-)

Question: In the `FinalClassificationData` packet the `m_best_lap_time_in_ms` is producing random timings, anywhere from 16ms to millions of ms none of which translate into meaningful lap times. I don't know if this is an issue with the UDP packet(s) but was wondering if you had seen the same?

Basically, I would like to capture the best lap time for a given race. Using Solo mode and quick race.

Many thanks!

**Comment by chrishannam** [comment]
Hi! Thank you for the kind words. I haven't noticed any issues, but I've mostly been playing/monitoring F122.
I'll have to see if I can have a look and confirm on F1 2021 as the issue might have carried over to F122

**Comment by rcastley** [comment]
Thank you for your reply ... I actually meant to post on your 2022 repo ... do you want to close this issue and I will replicate in the other one?

Thanks again!

**Comment by chrishannam** [comment]
Ah! Please recreate the issue, that would be great. I'm looking at it now actually...
